# Generated by Django 5.1.3 on 2024-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_tea_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='admin_notes',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderbundle',
            name='items',
        ),
        migrations.AlterField(
            model_name='orderbundle',
            name='request_cancellation',
            field=models.CharField(choices=[('No cancellation request', 'No cancellation request'), ('Cancellation requested', 'Cancellation requested')], default='No cancellation request'),
        ),
        migrations.AlterField(
            model_name='orderbundle',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Ready for Pick Up', 'Ready for Pick Up'), ('Cancelled by Customer', 'Cancelled by Customer'), ('Cancelled by management', 'Cancelled by management'), ('Completed', 'Completed')], default='Processing'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Premium', 'Premium')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='tea_variant',
            field=models.CharField(choices=[('Green', 'Green'), ('Black', 'Black')]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='request_cancellation',
            field=models.CharField(choices=[('No Cancellation request', 'No Cancellation request'), ('Cancellation requested', 'Cancellation requested')], default='No cancellation request'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Reserved', 'Reserved'), ('Cancelled by Customer', 'Cancelled by Customer'), ('Cancelled by management', 'Cancelled by management'), ('Completed', 'Completed')], default='Pending Approval'),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='orderbundle',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
