# Generated by Django 5.1.3 on 2024-12-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_tea_app', '0002_tour_admin_notes_remove_cart_items_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
