# Generated by Django 5.1.3 on 2024-12-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_tea_app', '0003_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_id_ref',
            field=models.CharField(default=''),
        ),
    ]
