# Generated by Django 5.1.3 on 2024-12-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_tea_app', '0004_cart_customer_id_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
