# Generated by Django 5.1.3 on 2025-03-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_tea_app', '0005_alter_customer_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(max_length=36)),
                ('user_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.AlterField(
            model_name='orderbundle',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Ready for Pick Up', 'Ready for Pick Up'), ('Cancelled by Customer', 'Cancelled by Customer'), ('Cancelled by management', 'Cancelled by management'), ('Completed', 'Completed')], default='PROCESSING'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Resolved', 'Resolved'), ('Archive', 'Archive'), ('Could not Resolve', 'Could not Resolve')], default='PROCESSING', max_length=20),
        ),
    ]
