# Generated by Django 5.1.3 on 2024-11-26 16:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=9, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('e-Cash', 'e-Cash'), ('Empty', 'Empty')], max_length=20)),
                ('total_cart_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=9)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('sum_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('product_description', models.TextField(default='')),
                ('product_type', models.CharField(choices=[('Classic', 'Classic'), ('Premium', 'Premium')], max_length=20)),
                ('tea_variant', models.CharField(choices=[('Green', 'Green'), ('Black', 'Black')], max_length=20)),
                ('inventory', models.IntegerField(default=0)),
                ('on_sale', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=9, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('ticket_details', models.TextField()),
                ('admin_notes', models.TextField()),
                ('email', models.EmailField(max_length=100)),
                ('customer_id', models.CharField(max_length=9)),
                ('customer_username', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Resolved', 'Resolved'), ('Could not Resolve', 'Could not Resolve')], default='Processing', max_length=20)),
                ('request_cancellation', models.CharField(choices=[('No Cancellation request', 'No Cancellation request'), ('Cancellation requested', 'Cancellation requested')], default='No Cancellation request', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.CharField(max_length=9, unique=True)),
                ('customer_username', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=9)),
                ('date', models.CharField(choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('time_slot', models.CharField(choices=[('10AM', '10AM'), ('3PM', '3PM')], max_length=20)),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Reserved', 'Reserved'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending Approval', max_length=20)),
                ('request_cancellation', models.CharField(choices=[('No Cancellation request', 'No Cancellation request'), ('Cancellation requested', 'Cancellation requested')], default='No Cancellation request', max_length=50)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('e-Cash', 'e-Cash')], max_length=20)),
                ('booked_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('price', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('headcount', models.IntegerField(default=1)),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=9, unique=True)),
                ('customer_username', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('joined', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='green_tea_app.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='green_tea_app.item'),
        ),
        migrations.CreateModel(
            name='OrderBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderbundle_id', models.CharField(max_length=9, unique=True)),
                ('customer_username', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=9)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('e-Cash', 'e-Cash'), ('Empty', 'Empty')], max_length=20)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('For Pick Up', 'For Pick Up'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Processing', max_length=20)),
                ('request_cancellation', models.CharField(choices=[('No Cancellation request', 'No Cancellation request'), ('Cancellation requested', 'Cancellation requested')], default='No Cancellation request', max_length=50)),
                ('notes', models.TextField(default='')),
                ('items', models.ManyToManyField(related_name='order_bundles', to='green_tea_app.item')),
            ],
        ),
    ]
